require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.sitter")
require("core.plugin_config.lsp_config")
require("core.plugin_config.completions")
require("core.plugin_config.nvim-web-devicons")
require("core.plugin_config.neoscroll")
require("core.plugin_config.mason")
